spring.application.name=Event_Consumer
spring.datasource.url=jdbc:postgresql://localhost:5432/event_db
spring.datasource.username=event_user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.secret-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
eventChangeNotification.stats.cron=0 0 0 ? * 1
springdoc.swagger-ui.url: /eventChangeNotification-notificator-openapi.yaml
